Services and repositories
AlexandrPotovichenko/ProjectManagement pull request #1
Opened 2021-10-08 16:46 UTC by AlexandrPotovichenko

Add Services and Repositories

2021-10-11 07:07 UTC, mykolazaiarnyi requested changes

2021-10-11 07:07 UTC, mykolazaiarnyi commented on ProjectManagement.BusinessLogic/Exceptions/GuardExtensions.cs
> +namespace Ardalis.GuardClauses
Please, name your namespaces the same as a path in a file system. In this case it should be `ProjectManagement.BusinessLogic.Exceptions`

2021-10-11 07:07 UTC, mykolazaiarnyi commented on ProjectManagement.BusinessLogic/Exceptions/GuardExtensions.cs
> +    public static class BoardGuards
Class name should be the same as a file name

2021-10-11 07:07 UTC, mykolazaiarnyi commented on ProjectManagement.BusinessLogic/Services/Implementation/BoardService.cs
> -        //private readonly IBoardMemberRepository _BoardMemberRepository;
It's considered a bad practice to keep commented code

2021-10-11 07:07 UTC, mykolazaiarnyi commented on ProjectManagement.BusinessLogic/Services/Interfaces/IBoardService.cs
> +        Task DeleteBoard(int boardId);
Please, add the `async` suffix to the name of async methods

2021-10-20 08:11 UTC, AlexandrPotovichenko commented
Fixed bugs.

2021-10-20 08:12 UTC, merged